### ISSUE TITLE
Endless cycle during scaning tag url 

### ISSUE THREAD

**Issue by ppisl** [olabini/jvyamlb#1]
NetBeans use this jvyamlb as a library for parsing yaml files. There is an issue in NetBeand Bugzilla (https://netbeans.org/bugzilla/show_bug.cgi?id=246124), which is mainly based on Out Of Memory exception that is caused by endless cycle in org.jvyamlb.ScannerImpl.scanTagUri() method. 

To reproduce this issue is enough to try parse an yaml file with this content:
--- !tag:%x?y foo

For NetBeans purposes is enough to break the cycle as is in the proposed patch. After applying the patch all tests in jvyamlb passed and also all test on NetBeans site as well.

**Comment by ppisl** [comment]
Proposed patch. This patch seems to be ok for NetBeans purposes. 

diff --git a/src/main/org/jvyamlb/ScannerImpl.java b/src/main/org/jvyamlb/ScannerImpl.java
index 5f2d66c..ea680e9 100644
--- a/src/main/org/jvyamlb/ScannerImpl.java
+++ b/src/main/org/jvyamlb/ScannerImpl.java
@@ -859,6 +859,7 @@ public class ScannerImpl implements Scanner {
                 chunks.append(this.buffer.bytes,this.pointer,length);
                 length = 0;
                 chunks.append(scanUriEscapes(name));
-                break;
           } else {
               length++;
           }

**Comment by ppisl** [comment]
I'm sorry, closed by mistake.

**Comment by olabini** [comment]
Thanks for the report! I'm looking at it, hopefully shouldn't be complicated. Your fix should work, but I think another way of fixing it is more appropriate. The problem is that the code forgets to forward the buffer pointer before resetting it.

**Comment by olabini** [comment]
OK, I've pushed this fix. I should just remember how to actually generate a new release for it as well. It was some time since... =)

**Comment by ppisl** [comment]
Hi,

I know that the fix is not probably the right one. I had to add it to the issue, due to the process that we have in NetBeans. When we are patching any external libraries, we have to publish somewhere the patch for satisfying lawyers rules:). 

Thanks for your work,

Petr

**Comment by olabini** [comment]
OK I just released 0.2.6. It's not in Maven, but you can download it all from the front page of the github project.

**Comment by olabini** [comment]
Actually, use 0.2.7, which is linked from the front page and should show up in the Maven repos any time soon.

**Comment by ppisl** [comment]
Thanks, from our site is always better to use official binary. When the links from front page will work, we will download the latest version. Thanks.

**Comment by olabini** [comment]
Damn, sorry about that. The official links are now working.
